### PR TITLE
Translate data.properties to Thai

### PR DESCRIPTION
**Pull request by OrneryCash**

### CODE REVIEW

**Comment by OrneryCash** [comment]
Translated change in the properties menu.
Screenshot 2567-07-29 at 1 14 05 PM

Choices:
Screenshot 2567-07-29 at 1 14 46 PM

**Review by BallballTH — COMMENTED** [review]
from 
"directionEastVertical = → ข้างขวา"
to
"directionEastVertical = → ด้านขวา"

i think this is better,isn't it?

**Comment by OrneryCash** [comment]
> from "directionEastVertical = → ข้างขวา" to "directionEastVertical = → ด้านขวา"
> 
> i think this is better,isn't it?

Oh right, yeah, I do think it's better. I'll make that changes now.

**Review by BallballTH — APPROVED** [review]
look noice

**Review by TeetatB — APPROVED** [review]
lgtm

**Pull request merged**
